// GENERATED by scripts/render-frames.mjs — do not edit by hand.
// Re-run `npm run frames` after changing any sequence.

export const frameSequences = {
  core: { path: "/frames", frameCount: 80 },
  corridor: { path: "/tunnel-frames", frameCount: 64 },
} as const;

export type FrameSequence = (typeof frameSequences)[keyof typeof frameSequences];
